name: PNXGiftCode
main: cn.innc11.giftcode.GiftCodePlugin
version: "1.9"
author: "innc&Reiyans&XKSHADOW"
api: ["1.0.9"]
description: gift code plugin
commands:
  giftcode:
    usage: "/code"
    aliases: ["code"]
    description: "open the panel of GiftCode"